module.exports = () => ({

    DATABASE_NAME: 'YOUR_MONGODB_DATABASE_NAME',
    DATABASE_URL: 'YOUR_MONGODB_CONNECTION_URL',

    SERVER_PORT: 8080,
    SERVER_CLIENT_URL: 'http://localhost:8000',

    SOCKETIO_CLIENT_CORS_ORIGIN: 'http://localhost:8000',
    SOCKETIO_CLIENT_CORS_METHODS: ['GET', 'POST', 'PUT', 'DELETE'],
    SOCKETIO_CLIENT_CORS_ALLOW_HEADERS: [],
    SOCKETIO_CLIENT_CORS_CREDENTIALS: true,
    SOCKETIO_CLIENT_MAX_HTTP_BUFFER_SIZE: 1e8,
    SOCKETIO_CLIENT_PING_TIME_OUT: 60000,

    MAILGUN_API_KEY: '',
    MAILGUN_DOMAIN: '',

    AWS_SES_AWS_ACCESS_KEY: '',
    AWS_SES_AWS_SECRET: '',
    AWS_SES_AWS_REGION: '',
    AWS_SES_MAIL_FROM: '',
    AWS_SES_EMAIL_TO: '',

    JWT_SECRET: '26VnXvf54y7GWEVzZ1lk6w3rzX9NgByO07LloVkEsKoCyHYVENwrholKVt31avVL',
    JWT_ACCOUNT_ACTIVATION: 'FNAmBAtcbtYESFKokgrpRyG84RPqM1ve457MeW0kYvWxGy65r8VMWRow79Fn2gTE',
    JWT_RESET_PASSWORD: 'wescYfxrL0xsWh1Cwn85tggk9QrWPCSnM4xAxg11vYQaQp9EzrazBdV68Wo6nVaq',
    JWT_TOKEN_SECRET: '26VnXvf54y7GWEVzZ1lk6w3rzX9NgByO07LloVkEsKoCyHYVENwrholKVt31avVL',
    JWT_TOKEN_EXPIRE_TIME: '10m',
    JWT_TOKEN_REFRESH_TOKEN_SECRET: 'wescYfxrL0xsWh1Cwn85tggk9QrWPCSnM4xAxg11vYQaQp9EzrazBdV68Wo6nVaq',
    JWT_TOKEN_REFRESH_TOKEN_EXPIRE_TIME: '10m',

    PASSWORD_HASH_SECRET: 'f:SPPemkx0HL_aY}|FQw>Ak1GZ]%lc[_xmv?<oTT6nWf0hR]Pˆ5<ZmHR]0Vxf}aL',
    PASSWORD_HASH_METHOD: 'sha256',

})